$file = ".\app\routes\auftragseingang.tsx"

$text = [System.IO.File]::ReadAllText((Resolve-Path $file))

$text = $text.Replace("AuftrÃ¤ge", "Aufträge")
$text = $text.Replace("AuftrÃ¤gen", "Aufträgen")
$text = $text.Replace("prÃ¼fen", "prüfen")
$text = $text.Replace("PrÃ¼fen", "Prüfen")
$text = $text.Replace("Ãœbernehmen", "Übernehmen")
$text = $text.Replace("Ãœbernommen", "Übernommen")
$text = $text.Replace("Ã¼bernehmen", "übernehmen")
$text = $text.Replace("Ã¼bernommen", "übernommen")
$text = $text.Replace("MenÃ¼", "Menü")
$text = $text.Replace("StÃ¼ck", "Stück")
$text = $text.Replace("â‚¬", "€")
$text = $text.Replace("fÃ¼r", "für")
$text = $text.Replace("spÃ¤ter", "später")
$text = $text.Replace("Ã¤", "ä")
$text = $text.Replace("Ã¶", "ö")
$text = $text.Replace("Ã¼", "ü")
$text = $text.Replace("ÃŸ", "ß")
$text = $text.Replace("Ã„", "Ä")
$text = $text.Replace("Ã–", "Ö")
$text = $text.Replace("Ãœ", "Ü")

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText((Resolve-Path $file), $text, $utf8NoBom)
