ALTER TABLE "EmailAccount" ADD COLUMN IF NOT EXISTS "imapHost" TEXT;
ALTER TABLE "EmailAccount" ADD COLUMN IF NOT EXISTS "imapPort" INTEGER;
ALTER TABLE "EmailAccount" ADD COLUMN IF NOT EXISTS "imapSecure" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "EmailAccount" ADD COLUMN IF NOT EXISTS "imapUsername" TEXT;
ALTER TABLE "EmailAccount" ADD COLUMN IF NOT EXISTS "imapPasswordEncrypted" TEXT;
ALTER TABLE "EmailAccount" ADD COLUMN IF NOT EXISTS "imapLastCheckedAt" TIMESTAMP(3);
ALTER TABLE "EmailAccount" ADD COLUMN IF NOT EXISTS "imapLastUid" TEXT;
